#MANGOHUD=1
#cpu_temp
#gpu_temp

# 0 means no limit
fps_limit=0
toggle_fps_limit=F1
# 1 = vsync off, 3 = vsync on
vsync=0

### CPU info 
cpu_temp 
cpu_text = 7800x3d

### GPU info
gpu_temp 
gpu_junction_temp
gpu_power
gpu_name 

### RAM/VRAM usage 
ram 
vram 

resolution

### Color customization 
text_color=FFFFFF 
gpu_color=de1f1f 
cpu_color=EB5B5B 
vram_color=752b50 
ram_color=752b50

toggle_hud=Shift_R+F12
toggle_logging=Shift_L+F2

#Added from https://github.com/flightlessmango/MangoHud/blob/master/data/MangoHud.conf
log_duration=60
#benchmark_percentiles=AVG,1,0.1
upload_log=F5
output_folder=/home/omni/.mangologs
